name: blr-says
version: 0.0.1a
summary: What does blr say?
description: A simple test snap to verify that deltas work as expected.

apps:
  blr-says:
    command: blr-says.py

parts:
  blr-says:
    plugin: python3
    source: .
